//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leonni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        // Primitive properties
    
        public long Id { get; set; }
        public string Title { get; set; }
        public int CategoryId { get; set; }
        public string Price { get; set; }
        public string Resume { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public string State { get; set; }
    
        // Navigation properties
    
        public virtual Category Category { get; set; }
    
    }
}
