//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leonni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Activities = new HashSet<Activity>();
            this.Articles = new HashSet<Article>();
            this.Links = new HashSet<Link>();
            this.Disciplines = new HashSet<Discipline>();
            this.UserProfiles = new HashSet<UserProfile>();
            this.Projects = new HashSet<Project>();
            this.Publications = new HashSet<Publication>();
        }
    
        // Primitive properties
    
        public int Id { get; set; }
        public int LanguageId { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> PageId { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual ICollection<Article> Articles { get; set; }
        public virtual ICollection<Link> Links { get; set; }
        public virtual ICollection<Discipline> Disciplines { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<Publication> Publications { get; set; }
    
    }
}
