//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leonni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        // Primitive properties
    
        public long ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Body { get; set; }
        public System.Guid ThreadID { get; set; }
        public System.Guid UserID { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public Nullable<long> ProfileId { get; set; }
    
    }
}
