//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leonni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentThread
    {
        // Primitive properties
    
        public System.Guid ID { get; set; }
        public string URL { get; set; }
        public Nullable<int> SectionId { get; set; }
        public Nullable<long> EntityID { get; set; }
    
    }
}
