//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leonni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrontContent
    {
        // Primitive properties
    
        public long Id { get; set; }
        public long SectionId { get; set; }
        public long ContentId { get; set; }
        public System.DateTime CreateDate { get; set; }
    
    }
}
