//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leonni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Activities = new HashSet<Activity>();
            this.Galleries = new HashSet<Gallery>();
        }
    
        // Primitive properties
    
        public long Id { get; set; }
        public bool IsVisible { get; set; }
        public bool IsCloseIncome { get; set; }
        public bool AllowContents { get; set; }
        public string Title { get; set; }
        public int DisciplineId { get; set; }
        public string Summary { get; set; }
        public string Text { get; set; }
        public string CountryName { get; set; }
        public int ProvinceId { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public long CreatedBy { get; set; }
        public int Status { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual Discipline Discipline { get; set; }
        public virtual ICollection<Gallery> Galleries { get; set; }
    
    }
}
