//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leonni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguageGroup
    {
        // Primitive properties
    
        public int LanguageGroupId { get; set; }
        public string LanguageGroupName { get; set; }
        public string LanguageSupported { get; set; }
    
    }
}
