//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leonni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.PageContents = new HashSet<PageContent>();
            this.Translations = new HashSet<Translation>();
            this.Sections = new HashSet<Section>();
        }
    
        // Primitive properties
    
        public int Id { get; set; }
        public string LanguageName { get; set; }
        public string LanguageCode { get; set; }
        public string LanguageDirection { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<PageContent> PageContents { get; set; }
        public virtual ICollection<Translation> Translations { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
    
    }
}
