//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leonni.Models
{
    using System;
    using System.Data.Entity;
    
    public partial class LeonniEntities : DbContext
    {
        public LeonniEntities()
            : base("name=LeonniEntities")
        {
        }
    
        public DbSet<Activity> Activities { get; set; }
        public DbSet<Advertisement> Advertisements { get; set; }
        public DbSet<Article> Articles { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Discipline> Disciplines { get; set; }
        public DbSet<Gallery> Galleries { get; set; }
        public DbSet<LanguageGroup> LanguageGroups { get; set; }
        public DbSet<Language> Languages { get; set; }
        public DbSet<Link> Links { get; set; }
        public DbSet<Month> Months { get; set; }
        public DbSet<PageContent> PageContents { get; set; }
        public DbSet<Page> Pages { get; set; }
        public DbSet<Translation> Translations { get; set; }
        public DbSet<FrontEntityFile> FrontEntityFiles { get; set; }
        public DbSet<VideoLink> VideoLinks { get; set; }
        public DbSet<FrontContent> FrontContents { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<Province> Provinces { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<EntityFile> EntityFiles { get; set; }
        public DbSet<Section> Sections { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<CommentThread> CommentThreads { get; set; }
        public DbSet<Year> Years { get; set; }
        public DbSet<Like> Likes { get; set; }
        public DbSet<File> Files { get; set; }
        public DbSet<Publication> Publications { get; set; }
        public DbSet<Favourite> Favourites { get; set; }
        public DbSet<Group> Groups { get; set; }
    }
}
