//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leonni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Like
    {
        // Primitive properties
    
        public long Id { get; set; }
        public Nullable<long> EntityId { get; set; }
        public string EntityName { get; set; }
        public Nullable<long> ProfileId { get; set; }
    
    }
}
