//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leonni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        // Primitive properties
    
        public long Id { get; set; }
        public long SentTo { get; set; }
        public System.DateTime SentDate { get; set; }
        public Nullable<long> SentBy { get; set; }
        public string MessageContent { get; set; }
    
    }
}
