//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leonni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageContent
    {
        // Primitive properties
    
        public int Id { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public string PageUrl { get; set; }
        public string PageName { get; set; }
        public string Content { get; set; }
        public string HyperLinkText { get; set; }
        public Nullable<bool> IsMarketingPage { get; set; }
        public string SortKey { get; set; }
    
        // Navigation properties
    
        public virtual Language Language { get; set; }
    
    }
}
