//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leonni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Activities = new HashSet<Activity>();
            this.Galleries = new HashSet<Gallery>();
            this.Links = new HashSet<Link>();
            this.Publications = new HashSet<Publication>();
        }
    
        // Primitive properties
    
        public long Id { get; set; }
        public string Title { get; set; }
        public int CategoryId { get; set; }
        public int DisciplineId { get; set; }
        public string CountryName { get; set; }
        public int StateId { get; set; }
        public string Cost { get; set; }
        public string Inversion { get; set; }
        public string Resume { get; set; }
        public string Description { get; set; }
        public string Link { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
        public Nullable<long> DeletedBy { get; set; }
        public Nullable<long> DisabledBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual Category Category { get; set; }
        public virtual Discipline Discipline { get; set; }
        public virtual ICollection<Gallery> Galleries { get; set; }
        public virtual ICollection<Link> Links { get; set; }
        public virtual ICollection<Publication> Publications { get; set; }
    
    }
}
