//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leonni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Province
    {
        // Primitive properties
    
        public int Id { get; set; }
        public Nullable<long> OBJECTID { get; set; }
        public Nullable<float> VertexCou { get; set; }
        public string ISO { get; set; }
        public string Country { get; set; }
        public string NAME_1 { get; set; }
        public string VARNAME_1 { get; set; }
        public string NL_NAME_1 { get; set; }
        public string HASC_1 { get; set; }
        public string TYPE_1 { get; set; }
        public string ENGTYPE_1 { get; set; }
        public string VALIDFR_1 { get; set; }
        public string VALIDTO_1 { get; set; }
        public string REMARKS_1 { get; set; }
        public string Region { get; set; }
        public string RegionVar { get; set; }
        public Nullable<int> ProvNumber { get; set; }
        public string NEV_Countr { get; set; }
        public string FIRST_FIPS { get; set; }
        public string FIRST_HASC { get; set; }
        public string FIPS_1 { get; set; }
        public Nullable<float> gadm_level { get; set; }
        public Nullable<int> CheckMe { get; set; }
        public string Region_Cod { get; set; }
        public string Region_C_1 { get; set; }
        public Nullable<int> ScaleRank { get; set; }
        public string Region_C_2 { get; set; }
        public string Region_C_3 { get; set; }
        public string Country_Pr { get; set; }
        public Nullable<float> Shape_Leng { get; set; }
        public Nullable<float> Shape_Area { get; set; }
    
    }
}
