//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leonni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public Section()
        {
            this.EntityFiles = new HashSet<EntityFile>();
            this.Favourites = new HashSet<Favourite>();
        }
    
        // Primitive properties
    
        public int Id { get; set; }
        public string SectionName { get; set; }
        public int LanguageId { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<EntityFile> EntityFiles { get; set; }
        public virtual Language Language { get; set; }
        public virtual ICollection<Favourite> Favourites { get; set; }
    
    }
}
