//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leonni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translation
    {
        // Primitive properties
    
        public long Id { get; set; }
        public int LanguageId { get; set; }
        public string Classification { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
        public string PageUrl { get; set; }
        public string GroupName { get; set; }
    
        // Navigation properties
    
        public virtual Language Language { get; set; }
    
    }
}
