//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leonni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersProfile
    {
        // Primitive properties
    
        public long Id { get; set; }
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string SurName { get; set; }
        public int CategoryId { get; set; }
        public int DisciplineId { get; set; }
        public string Summary { get; set; }
        public string Description { get; set; }
        public string Occupation { get; set; }
        public string Company { get; set; }
        public string Sex { get; set; }
        public string Birth { get; set; }
        public string Phone { get; set; }
        public string WebLink { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> StateId { get; set; }
        public string Locality { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
    
    }
}
