//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leonni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        // Primitive properties
    
        public long Id { get; set; }
        public System.Guid UserId { get; set; }
        public string FirstName { get; set; }
        public string SurName { get; set; }
        public int CategoryId { get; set; }
        public int DisciplineId { get; set; }
        public string Summary { get; set; }
        public string Description { get; set; }
        public string Occupation { get; set; }
        public string Company { get; set; }
        public string Sex { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Phone { get; set; }
        public string WebLink { get; set; }
        public string CountryName { get; set; }
        public int StateId { get; set; }
        public string Locality { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsLeonniTeam { get; set; }
        public Nullable<long> LikesCount { get; set; }
        public Nullable<long> CommentsCount { get; set; }
        public int StatusId { get; set; }
        public Nullable<long> VisitorsCount { get; set; }
    
        // Navigation properties
    
        public virtual Category Category { get; set; }
        public virtual Discipline Discipline { get; set; }
    
    }
}
