//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leonni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Year
    {
        // Primitive properties
    
        public int Id { get; set; }
        public int LanguageId { get; set; }
        public string YearName { get; set; }
    
    }
}
